version: "3.8"

services:
  # Backend server
  server:
    build:
      context: .
      dockerfile: Dockerfile.server
    container_name: mcp-host-server
    restart: unless-stopped
    ports:
      - "4000:4000"
    environment:
      - NODE_ENV=production
      - PORT=4000
      - CLIENT_URL=http://localhost:3000
    volumes:
      - ./server/logs:/app/logs
    networks:
      - mcp-network

  # Frontend client
  client:
    build:
      context: .
      dockerfile: Dockerfile.client
    container_name: mcp-host-client
    restart: unless-stopped
    ports:
      - "3000:3000"
    # Remove runtime environment variable, it's baked into the build now
    depends_on:
      - server
    networks:
      - mcp-network

networks:
  mcp-network:
    driver: bridge
